name: Push Docker image to Github Registry

on:
  push:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: wsd2019
  IMAGE_TAG: latest

jobs:
  build:
    name: Build image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      - name: Download files
        run: ./download_files.sh
      - name: Build image
        run: |
          export REPO_NAME=`echo ${{ github.repository }} | tr [:upper:] [:lower:]`
          docker build -t docker.pkg.github.com/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG} --file Dockerfile .
      - name: Push image to GitHub Registry
        run: |
          export REPO_NAME=`echo ${{ github.repository }} | tr [:upper:] [:lower:]`
          docker push docker.pkg.github.com/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}